name: CI pipeline



on:
  push:
    branches:
      - main
  pull_request:


jobs:
  project-testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirement.txt
          pip install dvc

      - name: Run DVC pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.MLOPS_FULL }}
        run: |
          dvc repro